#1. Note: By default YAML Configuration is store with the name of ?
## Azure-Pipeline.yml
#Like: name:NetCoreMicroserviceCiCd
#trigger:
# -master
#pool: 
 # VmImage:ubuntu-latest
#variables:
#buildconfiguration: "Release"

##2. I don't want to run my pipeline from any branch? i want to make it manually?
# Like: name:netcoremicroserviceCiCd
#trigger: none (disable trigger only)
# pool:
# vmimage: ubuntu-latest
# variables
# buildconfiguration: "Release"

###3. I want trigger my pipleline from both devlopment branch and Release branch? How it is possible?

# name:netcoremicroservicecicd
# trigger:
# - devlopment
# - Release
# pool:
# vmimage: 
# vmimage: ubuntu-latest
# variables:
# buildconfiguration: "Release"

####4. you identified the issue at one repository at one particular file.
# then, i want to trigger that particular file only? is it possible??
# Solution: Yes, it is possible.

#name: netcoremicroservice
#trigger: 
# - master
# INCLUDEEXCLUDEFILTERS:
# INCLUDE:    (here we want to include the path of the file.)
#(particularlly which you want to trigger)
#pool: 
# vmimage: ubuntu-latest
#variables: 
#buildconfiguration: "Release"

#or

#name: netcoremicroservice
#trigger: 
# batch: true
# brannches: 
# Include: 
# - features/* (ex for one senario)
# Exclude:
# -features/* (ex for one sinario)
# paths:
# exclude:
# - java.util (only java.util will exclude)
# pool: 
# vmimage: ubuntu-latest
# variables:
# buildconfiguration: "Release"

# this how only particular file will trigger within 5 min rather then 30 min
# this how we change the triggering point of your pipeline.


#####5 I want to schdule my pipeline at particular time only?
# like i want to trigger my pipeline at midnidght 12:00AM only> is it possible?

# yes, it is possible.
# name:netcoremicroservicecicd
# trigger:
#    - master

# schdules: 
# - corn: "0.0.*.*.*" (0 minutes, 0 hours means: midnight 12:00AM)
# displayname: dailyMidghtbuild
# branches: 
# Include:
# - master

# pool: vmimage: ubuntu-latest
# variables: 
# buildconfiguration: "Release"


### ###.6 Is it possible if i want to trigger my piprline there is no no code changes? in any repository?
# yes, it is possible.

# name: netcoremicroservicecicd
# trigger:
# - master


# schdules:
# - corn: "0.0.*.*.*"
# display name: "daily midnight build"
# branches: 
# Include:
# - master
# Always: true


# pool: 
# VmImage: ubuntu-latest
# Variables: 
# buildconfiguration: "Release"

### ### # . PULL REQUIREST
# Merging the code from one branch to another branch.
# Pull requirest trigger cause a pipeline to run whenever pull requirest is opened.
# Once you done the pull requirest the cause the pipeline.
#once we raise the pull requirest is opened here.
#
 # name: netcoremicroservicecicd
 

 # pr: 
 # - main
 # release/*
 

#so this architecture runs a new run, the first time new pull requirest is created.
# after every update pull requirest
# 1st it will run new release branch
# then it will run new release branch
# then, it is fine. then it automatically merge the code.

# pool: 
# vmimage: ubuntu-latest
# variables:
# buildconfiguration: "Release"



# we detect the pipelines in 2 methods.
# 1. CI Trigger.
# 2. PR trigger.

#1. CI Trigger: 
# name: netcoremicroservicecicd
# trigger: 
# - master
# pool:
# vmimage: ubuntu-latest
# variables: 
# buildconfigurations: "Release"

#2 PR Trigger
# Pull Requirest.

# this 2 methods your pipeline will trigger.

#### ####.8  Demands:
# when you defined any agent.
# agent want to specify the particular software or version which needed Demands.
# If i want to install only specific dot . Net meachine or dot .Net specific version of agent then we use Demands.

# Name: netcoremicroservicecicd
# trigger: 
# - master
# pool: 
# vm image: windows-latest
# demands: 
# name -equal windows-NT
#(It means windows machine, windows family it will get Windows-NT operating system agent to run this build)
#  variables:
# buildconfiguration: "Release"




