Name: NetcoreMicroserviceCiCd
Trigger:
- master
Pool:
VmImage: ubuntu-latest
varables:
buildconfiguration: "Release"
parameters:
  - name: image
  displayname: poolImage
  type: string
  default: ubuntu-latest
  values:
  -windows-latest
  -ubuntu-latest
  -macOs-latest
  jobs:
    - build
    displayname: "build"
    pool:
    vmimage: ${{parameters.image}}
    steps:
      - script: echo "hellow-world"
      