name: NetcoreMicroserviceCiCd
trigger:
- master
pool:
vmimage: ubuntu-latest
varables:
buildconfiguration: "Release"
parameters:
  - name: image
  #displayname: Pool Image
  displayName: pool Image
  type:string
  default:ubuntu-latest
  values
  - windows-latest
  - ubuntu-latest
  - MacOs-latest
  #